version: "3.8"
services:
  dynamodb:
    container_name: dynamodb
    image: "amazon/dynamodb-local:1.18.0"
    command:
      - -jar
      - DynamoDBLocal.jar
      - -sharedDb
      - -optimizeDbBeforeStartup
      - -dbPath
      - ./data
    ports:
      - 8000:8000
    volumes:
      - dynamodbvolume:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - back-tier
volumes:
  dynamodbvolume: {}
networks:
  back-tier: {}
