version: "3.8"
services:
  dynamodb:
    container_name: dynamodb
    image: "amazon/dynamodb-local:1.18.0"
    command:
      - -jar
      - DynamoDBLocal.jar
      - -sharedDb
      - -optimizeDbBeforeStartup
      - -dbPath
      - ./data
    ports:
      - 8000:8000
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - back-tier
  sqs:
    container_name: sqs
    image: localstack/localstack:0.13.3.3-arm64
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=sqs
      - LAMBDA_DOCKER_NETWORK=magnifibot_back-tier
    volumes:
      - localstack_tmp:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - back-tier
volumes:
  # dynamodbvolume: {}
  localstack_tmp: {}
networks:
  back-tier: {}
