version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:6.2.6-alpine3.15
    command:
      - redis-server
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
    ports:
      - 6379:6379
    volumes:
      - redisvolume:/data
    networks:
      - back-tier
volumes:
  redisvolume: {}
networks:
  back-tier: {}
