version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:6.2.6-alpine3.15
    command:
      - redis-server
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
    ports:
      - 6379:6379
    volumes:
      - redisvolume:/data
    networks:
      - back-tier
  dynamodb:
    container_name: dynamodb
    image: "amazon/dynamodb-local:1.18.0"
    command:
      - -jar
      - DynamoDBLocal.jar
      - -sharedDb
      - -optimizeDbBeforeStartup
      - -dbPath
      - ./data
    ports:
      - 8000:8000
    volumes:
      - dynamodbvolume:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - back-tier
volumes:
  redisvolume: {}
  dynamodbvolume: {}
networks:
  front-tier: {}
  back-tier: {}
