name: Bump tag and version
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - serverless.yml
      - .github/workflows/deploy-prod.yml
      - '!main.go'
      - go.*
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
  deploy-in-prod:
    needs: tag
    uses: ./.github/workflows/deploy-prod.yml
    with:
      github_tag: ${{ needs.tag.outputs.new_tag }}
