name: Test the project
on:
  push:
    paths:
      - '**.go'
      - '!main.go'
      - go.*
jobs:
  test:
    if: github.ref_name != "main"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Test the project
        run: |
          go test ./...
